CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(120) NOT NULL,
    role VARCHAR(120) NOT NULL,
    date_applied DATE NOT NULL,
    url VARCHAR(2048) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('Applied', 'Interview', 'Rejected', 'Offer')),
    notes VARCHAR(2000) NOT NULL
);
